config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  resources :profiles, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :quests do
    resources :participations, only: [:create]
  end
  resources :participations, only: [:index, :destroy, :edit] do
    patch :finish_participation
    resources :reviews, only: [:new, :create]
  end
  resources :comparisons, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carbone_print.rb
class CarbonePrint < ApplicationRecord
  belongs_to :user
  belongs_to :quest
end

app/models/participation.rb
class Participation < ApplicationRecord
  # Relations
  #
  belongs_to :user
  belongs_to :quest
  has_many :reviews, dependent: :destroy
  after_create :set_carbone_print

  # Scopes
  #
  scope :pasted, lambda { where.not(end_date: nil)}
  scope :currents, lambda { where(end_date: nil)}

  # List of actions to trigger when user finish quest
  #
  def finish_quest
    increment_user_score
    increment_user_carbone_print
  end

  private

  def set_carbone_print
    CarbonePrint.create(user: user, quest: quest)
  end

  def increment_user_score
    new_quest_point = self.quest.points.to_i
    updated_score = self.user.score.to_i + new_quest_point

    user.update(score: updated_score)
  end

  def increment_user_carbone_print
    new_quest_foot_print = quest.points.to_i / 10
    updated_foot_print = self.user.foot_print.to_i - new_quest_foot_print

    user.update(foot_print: updated_foot_print)
  end

end

app/models/quest.rb
class Quest < ApplicationRecord
  has_one_attached :photo
  has_many :participations, dependent: :destroy
  has_many :users, through: :participations
  has_many :reviews, through: :participations, dependent: :destroy


  def truncate_content
    content[0, 60] + "..."
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :participation
  has_one :user, through: :participation
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :carbone_print, dependent: :destroy
  has_many :participations, dependent: :destroy
  has_many :quests, through: :participations, dependent: :destroy
  has_many :reviews, through: :participations, dependent: :destroy


  validates_presence_of :username
  validates_uniqueness_of :username

  def planets
    (self.foot_print / 1000.to_f) * 2.5
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/carbone_prints_controller.rb
class CarbonePrintsController < ApplicationController
end

app/controllers/comparisons_controller.rb
class ComparisonsController < ApplicationController
  skip_after_action :verify_policy_scoped, only: :index
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  def index
    # @participations = Participation.all
    @participations = policy_scope(Participation)
    @past_participations = @participations.pasted
    @current_participations = @participations.currents
  end

  def create
    @quest = Quest.find(params[:quest_id])
    @participation = Participation.new
    @participation.quest = @quest
    @participation.user = current_user
    authorize @participation
    if @participation.save
      redirect_to profile_path(current_user)
    else
      render :new
    end
  end

  def edit
    @participation = Participation.find(params[:id])
    authorize @participation
  end

  def update
    @participation.user = current_user
    authorize @participation
    @participation.update
    redirect_to edit_participations_path
  end

  def destroy
    @participation = Participation.find(params[:id])
    authorize @participation
    @participation.destroy
    redirect_to profile_path(current_user)
  end

  def finish_participation
    @participation = Participation.find(params[:participation_id])
    authorize @participation
    @participation.end_date = Date.today
    if @participation.save
      @participation.finish_quest
      redirect_to profile_path(current_user)
    else
      flash[:alert] = "Oups, quelque chose ne va pas. Essayez encore !"
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = User.find(params[:id])
    authorize @profile
    @participations = policy_scope(Participation)
    @my_past_participations = @participations.pasted.order("created_at DESC")
    @my_current_participations = @participations.currents.order("created_at DESC")
  end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController

  def index
    @quests = policy_scope(Quest)
    @level_1 = policy_scope(Quest).where(points: 0..100)
    @level_2 = policy_scope(Quest).where(points: 101..200)
    @level_3 = policy_scope(Quest).where(points: 201..400)
  end

  def show
    @quest = Quest.find(params[:id])
    authorize @quest
    @participation = Participation.new
  end

  def quest_params
    params.require(:quest).permit(:title, :content, :duration, :points)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_participation, only: [:create]

  def create
    @review = Review.new(review_params)
    @review.participation = @participation
    @quest = @participation.quest
    if @review.save
      redirect_to quest_path(@quest)
    else
      render :new
    end
  end

  private

  def set_participation
    @participation = Participation.find(params[:participation_id])
    authorize @participation
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def pages_home?
    params[:controller] == 'pages' && params[:action] == 'home'
  end

  def pages_quests_index?
    params[:controller] == 'quests' && params[:action] == 'index'
  end

  def pages_quests_show?
    params[:controller] == 'quests' && params[:action] == 'show'
  end

  def pages_profile_show?
    params[:controller] == 'profiles' && params[:action] == 'show'
  end

  def pages_earth?
    params[:controller] == 'comparisons' && params[:action] == 'index'
  end

end

app/views/comparisons/index.html.erb
<div class="compare">
  <img class="earth-stars" src=<%= image_path("stars.png") %> alt="">
  <img class="earth-stars" src=<%= image_path("stars.png") %> alt="">
  <img class="earth-stars" src=<%= image_path("stars.png") %> alt="">
  <div class="earth_needed text-center m-2">
    <h4>Si tout le monde vivait</h4>
    <h4>comme toi, il faudrait :</h4>
    <h1><strong><%= current_user.planets.round(1) %></strong> planètes
    </h1>
  </div>
  <div class="earth pt-2 mb-3">
    <% current_user.planets.truncate.times do %>
      <%= image_tag "terre.png", class: "full-earth" %>
    <% end %>
    <% if current_user.planets > current_user.planets.truncate %>
      <%= image_tag "half-terre.png", class: "half-earth" %>
    <% end %>
  </div>
  <h4 class="text-center"><i class="fas fa-shoe-prints"></i></i> carbone dans le monde</h4>
  <div class="graph_d" style="width:330px" id="graph_d" data-footprints="<%= [((current_user.foot_print) / 100.0).round(1), 11.9, 15.5, 12.3, 8.7].to_json %>" data-profile-picture="<%= image_path("avatar-jeremy-zoom.png")%>"></div>
  <div id='graph_javascript_first' class="pt-4">
  </div>
  <div id='graph_javascript_second'>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Colibri</title>
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <!-- Facebook -->
    <meta property="og:title" content="Colibri - Faire sa part">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://www.colibri.herokuapp.com/">
    <%= favicon_link_tag "colibri_favicon.png" %>
    <meta name="viewport" content="width=320, initial-scale=1">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <link href="https://fonts.googleapis.com/css?family=Slabo+27px&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/highcharts-3d.js"></script>
    <script src="https://code.highcharts.com/modules/cylinder.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
  </head>
  <body id="<%= controller.controller_name %>-<%= controller.action_name %>">
    <% if pages_home? == false %>
      <%= render 'shared/navbar' %>
    <% end %>
    <% if pages_home? %>
      <div class="content-wrapper-home">
    <% elsif pages_quests_index? %>
      <div class="content-wrapper-quests-index">
    <% elsif pages_quests_show?%>
      <div class="content-wrapper-quests-show">
    <% elsif pages_profile_show? %>
      <div class="content-wrapper-profile-show">
    <% elsif pages_earth? %>
      <div class="content-wrapper-earth">
    <% else %>
      <div class="content-wrapper">
    <% end %>
        <%= yield %>
      </div>

    <% if pages_home? == false %>
      <%= render 'shared/footer' %>
    <% end %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="pt-5">
  <div class="d-flex justify-content-center colibri pt-3">
    <%= image_tag "hummingbird-02.svg", alt: "alttext" %>
  </div>
  <div class="d-flex justify-content-center align-items-center my-3">
    <h1 class="font-home">Colibri</h1>
  </div>
  <div class="d-flex justify-content-center align-items-center pt-5">
    <%= link_to 'START', profile_path(current_user), class: "example-1" %>
  </div>
</div>

app/views/participations/_current_participation.html.erb
<% participations.each do |participation| %>
  <div class="card-product-wrapper">
    <div class="card-product mt-2">
      <div class="card-quest-image w-100">
      <%= link_to quest_path(participation.quest) do %>
        <%= cl_image_tag(participation.quest.photo.key) %>
      </div>
      <% end %>
      <div class="card-product-infos d-flex flex-column flex-grow-1">
        <h6> <%= participation.quest.title %></h6>
        <div class="score_information">
          <h6> <%= participation.quest.points %> pts</h6>
        </div>
      </div>
      <div class="card-product-actions">
        <div class="d-flex justify-content-center">
          <%= link_to participation_finish_participation_path(participation), method: :patch, remote: true do %>
            <button type="button" class="btn btn-color"><strong>Challenge réussi !</strong></button>
          <% end %>
        </div>
        <div class="mx-5 my-2">
          <%= link_to "🐎 La quête ne me plait plus", participation_path(participation), method: :delete, remote: true, class: "btn-delete", data: { confirm: "Êtes-vous certain de vouloir supprimer cette quête ?" } %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/participations/_index.html.erb
<div class="container bg-2">
  <div class="title-reservation pt-2">
    <h2> <strong>Toutes mes quêtes</strong> </h2>
  </div>
  <br>
  <div class="container m-2">
    <h5> <strong>Mes quêtes en cours:</strong> </h5>
    <div id="resa-actual" class="resa-container">
      <%= render "participations", participations: @current_participations %>
    </div>
    <br>
    <h5> <strong>Mes quêtes passées:</strong> </h5>
    <div id="resa-past" class="resa-container">
      <%= render "participations", participations: @past_participations %>
    </div>
  </div>
</div>

app/views/participations/_participation.html.erb
<% participations.each do |participation| %>
  <div class="card-product-wrapper">
    <div class="card-product mt-2">
      <%= link_to quest_path(participation.quest) do %>
        <%= cl_image_tag(participation.quest.photo.key, crop: :fill) %>
    <% end %>
      <div class="card-product-infos d-flex flex-column flex-grow-1">
          <h6> Quête : <%= participation.quest.title %></h6>
          <h6> Score: <%= participation.quest.points %> points</h6>
      </div>

      <div class="card-product-actions pr-4">
        <div class="mx-4">
          <%= link_to participation_finish_participation_path(participation), method: :patch do %>
            <button type="button" class="btn btn-success">J'ai réussi mon challenge !</button>
          <% end %>
        </div>
        <div class="mx-5 my-2">
          <%= link_to "La quête ne me plait plus :(", participation_path(participation), method: :delete, class: "btn-delete", data: { confirm: "Êtes-vous certain de vouloir supprimer cette quête ?" } %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/participations/_participations_index_partial.html.erb
<% if @profile.participations.currents.any? %>
  <div class="d-flex justify-content-center">
    <h5 class="number-quests-current mt-3"> <strong>Mes quêtes en cours </strong><span><%= @profile.participations.currents.count %></span></h5>
  </div>
<% end %>
<div id="resa-actual" class="resa-container">
  <%= render "../views/participations/current_participation.html.erb", participations: locals[:participations_current] %>
</div>

<div class="d-flex justify-content-center">
  <h5 class="number-quests-past mt-3"> <strong>Mes quêtes passées </strong><span><%= @profile.participations.pasted.count %></span></h5>
</div>
<div id="resa-past" class="resa-container">
  <%= render "../views/participations/past_participation", participations: locals[:participations_past] %>
</div>

app/views/participations/_past_participation.html.erb
<% participations.each do |participation| %>
  <div class="card-product-wrapper">
    <div class="card-product opacity-past mt-2">
      <div class="card-quest-image w-100">
      <%= link_to quest_path(participation.quest) do %>
        <%= cl_image_tag(participation.quest.photo.key) %>
      </div>
      <% end %>
      <div class="card-product-infos d-flex flex-column flex-grow-1">
        <h6> <%= participation.quest.title %></h6>
        <div class="score_information">
          <h6> <%= participation.quest.points %> pts</h6>
        </div>
      </div>
      <div class="card-product-actions">
        <%= render "./participations/review_form_modal", participation: participation %>
      </div>
    </div>
  </div>
<% end %>

app/views/participations/_review_form_modal.html.erb
<!-- Button trigger modal -->
<div class="mx-4 mb-4">
  <button type="button" class="btn btn-color" data-toggle="modal" data-target="#reviewModal_<%= participation.id %>">
    <%= link_to 'Voir mon impact 🌚', comparisons_path(current_user) %>
    </button>
</div>

app/views/participations/_show.html.erb
<div class="container bg-2">
  <div class="title-reservation pt-2">
    <h2> <strong>Toutes mes quêtes</strong> </h2>
  </div>
  <br>
  <div class="container m-2">
    <h5> <strong>Mes quêtes en cours:</strong> </h5>
    <div id="resa-actual" class="resa-container">
      <%= render "participations", participations: @current_participations %>
    </div>
    <br>
    <h5> <strong>Mes quêtes passées:</strong> </h5>
    <div id="resa-past" class="resa-container">
      <%= render "participations", participations: @past_participations %>
    </div>
  </div>
</div>

app/views/participations/index.html.erb
<%= render "participations_index_partial", locals: {participations_past: @past_participations, participations_current: @current_participations} %>

app/views/profiles/show.html.erb
<div class="position container-fluid">
  <div class="row d-flex justify-content-center pt-3">
    <div class="clouds">
      <img class="profile-cloud1" src=<%= image_path("cloud1.png") %> alt="">
      <img class="profile-cloud3" src=<%= image_path("cloud3.png") %> alt="">
    </div>
    <h3 class="profile-username pt-2"> <strong><%= @profile.username %></strong></h3>
    <div class="d-flex align-items-center pt-2">
      <div class="profile-user-card mb-2 mx-2">
          <p class="profile-user-title"><i class="fas fa-star"></i> score </p>
          <p class="profile-user-infos"><strong><%= @profile.score %></strong> pts</p>
      </div>
      <div class="profile-user-card mb-2 mx-2">
          <p class="profile-user-title"><i class="fas fa-shoe-prints"></i></i> carbone </p>
          <p class="profile-user-infos"><strong><%= ((@profile.foot_print) / 100) %></strong> T / C02 e</h2>
      </div>
    </div>
  </div>
  <%= render "./participations/participations_index_partial", locals: {participations_past: @my_past_participations, participations_current: @my_current_participations} %>
  </div>
</div>

app/views/quests/_cards_level.html.erb
<% level.each do |quest| %>
  <%= link_to quest_path(quest) do %>
    <div class="card-quest-infos">
      <%= cl_image_tag quest.photo.key, alt: "alttext" %>
      <h3><%= quest.title %></h3>
      <p class="card-quest-points"><span><%= quest.points %></span> pts</p>
      <p class="card-quest-starter">Go!</p>
    </div>
  <% end %>
<% end %>

app/views/quests/index.html.erb
<div class="levels-position" id="container-levels">
  <img class="cloud-1" src=<%= image_path("cloud1.png") %> alt="">
  <img class="cloud-3" src=<%= image_path("cloud3.png") %> alt="">
  <img class="farm" src=<%= image_path("farmdown.png") %> alt="" style="width: 100vw !important">
  <div class="card-level color-level-1">
    <div class="card-width">
      <%= render "../views/quests/cards_level", level: @level_1 %>
    </div>
      <h3 class="title-quest-level" id="title-level-one">FACILE <span><i class="far fa-star"></i></span></h3>
      </span></h3>
  </div>

  <div class="card-level color-level-2">
    <div class="card-width">
      <%= render "../views/quests/cards_level", level: @level_2 %>
    </div>
      <h3 class="title-quest-level" id="title-level-two">MOYEN <span><i class="far fa-star"></i><i class="far fa-star"></i></span></h3>
  </div>

  <div class="card-level color-level-3">
    <div class="card-width">
      <%= render "../views/quests/cards_level", level: @level_3 %>
    </div>
      <h3 class="title-quest-level" id="title-level-three">DIFFICILE <span><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i></span></h3>
  </div>
</div>

app/views/quests/show.html.erb
<div class="container-fluid container-position">
  <div class="back">
    <%= link_to quests_path, class: 'comeback' do %>
      <%= image_tag('arrow.svg', height: 20, width: 20) %>
    <% end %>
  </div>
  <div class="row justify-content-center">
    <div class="titre_1 w-100">
      <div class="quest-image" style="background: url('<%= cl_image_path @quest.photo.key , alt: "alttext" %>')">
        <p class="score m-0"><span><%= @quest.points %></span> pts</p>
      </div>
      <div class="title_quest m-2">
        <h2>
          <strong><%= @quest.title %></strong>
        </h2>
      </div>
    </div>
    <div class="card-description-quest">
      <div class="description_quest1 m-2">
        <p>
          <i class="fas fa-tree"></i>
          <%= @quest.content %>
        </p>
      </div>
      <div class="description_quest2 m-2">
        <p>
          <i class="fab fa-pagelines"></i>
          <%= @quest.content_2 %>
        </p>
      </div>
      <% if @quest.content_3 %>
        <div class="description_quest3 m-2">
          <p>
            <i class="fas fa-leaf"></i>
            <%= @quest.content_3 %>
          </p>
        </div>
    </div>
      <% end %>
  </div>
  <div class="mx-auto" style="width: 200px;">
    <%= simple_form_for([@quest, @participation]) do |f| %>
      <%= f.submit "Accepter cette quête ?", class: 'btn btn-color mb-4 font-weight-bold' %>
    <% end %>
  </div>
  <div class="list-group">
    <h4>Commentaires</h4>
    <% @quest.reviews.each do |review| %>
    <div class="card-review">
      <h5><%= review.user.username %></h5>
      <div>
        <%# if review.rating %>
        <% rating = review.rating %>
        <% stars = 0 %>
        <% until stars == rating %>
          <i class="fas fa-star star-rating"></i>
          <% stars += 1 %>
        <% end %>
          <%# review.rating.times do |i| %>
<!--               <a href="#" data-rating-value=<%#=i%> data-rating-text=<%#= i %> class="br-selected br-current"></a> -->
          <%# end %>
        <%# end %>
      </div>
      <p><%= review.content %></p>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<% if user_signed_in? %>
<div class="footer footer-links fixed-bottom">
  <%= link_to profile_path(current_user) do %>
  <div class="personnal"></div>
    <%#= image_tag('personnal.svg', height: 50, width: 50, class: 'personnal') %>
  <% end %>
  <%= link_to quests_path do %>
    <div class="quests"></div>
    <%#= image_tag('quests.svg', height: 50, width: 50, class: 'quests') %>
  <% end %>
  <%= link_to comparisons_path(current_user) do %>
    <div class="world"></div>
    <%#= image_tag('world.svg', height: 50, width: 50, class: 'world') %>
  <% end %>
</div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="navbar-items">
    <div class="title">
      <p>Level 1</p>
    </div>
    <div class="avatar">
      <%= image_tag "avatar-jeremy-zoom.png", class: "avatar avatar-border" %>
    </div>
    <div class="badge">
      <%= image_tag "badge2.svg", height: 45, width: 45 %>
    </div>
  </div>
<% end %>